---
- name: Copy join command  to local file for master node
  copy:
    content: "{{ hostvars['taghtaghoo']['kubermast'] }} --apiserver-advertise-address {{ ansible_host }}"
    dest: "/root/join-command-masternode.sh"
    mode: 777

- name: Join the Master
  command: sh "/root/join-command-masternode.sh"

- name: touch the file if its not exist
  file:
    path: "/etc/default/kubelet"
    state: touch
- name: create rule for "/etc/default/kubelet"
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip="{{ ansible_host }}"
  notify: kubelet restart