---
- name: Disable the ufw firewall (on Ubuntu, if configured).
  service:
    name: ufw
    state: stopped
    enabled: false

- name: Remove unwanted packages
  apt:
    pkg:
      - snapd 
      - samba-common 
      - smbclient 
      - lxd 
      - lxcfs 
      - open-iscsi
    state: absent

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install packages that allow apt to be used over HTTPS
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes
    
- name: make some change on sysctl
  shell: echo "net.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-iptables = 1" >> /etc/sysctl.d/kubernetes.conf

- name: apply change on sysctl
  shell: sysctl --system

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    mode: 600

- name: Install docker and its dependecies
  apt: 
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io  
    state: present
    update_cache: yes
  notify:
    - docker status

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
    mode: 600

- name: Install Kubernetes binaries
  apt: 
    pkg:
      - kubelet 
      - kubeadm 
      - kubectl
    state: present
    update_cache: yes